Importing the dependencies

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

Data Collection and Processing

In [4]:
# loading the dataset to pandas dataframe
dataset = pd.read_csv("/WW10.csv")

In [5]:
dataset.describe()

                 z          tip       sleeve
count  1085.000000  1085.000000  1085.000000
mean     13.575000    16.492598   609.582212
std       7.833921     7.402253   337.204127
min       0.025000     3.406400     0.000000
25%       6.800000    12.118300   324.051800
50%      13.575000    16.621800   647.146100
75%      20.350000    20.212700   825.163900
max      27.125000    55.042700  1848.646800

In [6]:
dataset.head()

       z      tip    sleeve
0  0.025  13.7644   48.9334
1  0.050  55.0427   68.6599
2  0.075  50.4913   88.3865
3  0.100  32.7215   98.6328
4  0.125  33.5907  145.0764

In [7]:
# to find the number of missing values in each column to later clean those rows
dataset.isnull().sum()

z         0
tip       0
sleeve    0
dtype: int64

In [8]:
# So no row in the cell is empty and we can proceed with the given data
dataset['Rf'] = ((dataset['sleeve'] / 1000)/dataset['tip'])*100

In [9]:
# checking if the new column ' Rf' is created
dataset.head()

       z      tip    sleeve        Rf
0  0.025  13.7644   48.9334  0.355507
1  0.050  55.0427   68.6599  0.124739
2  0.075  50.4913   88.3865  0.175053
3  0.100  32.7215   98.6328  0.301431
4  0.125  33.5907  145.0764  0.431895

In [10]:
# Classifying the soil type based on the Rf value we derived, function of determining the soil type based on the Rf value
def classify_soil(Rf):
  if Rf <= 1:
    return 'Sand'
  elif Rf <= 4:
    return 'Silty Sand'
  elif Rf <= 7:
    return 'Silt'
  else:
    return 'Clay'

#Adding another column into the dataset after applying the function 'classify_soil' to the Rf value in the data
dataset['soil_type'] = dataset['Rf'].apply(classify_soil)

#checking the data if the row 'soil_type' got added
dataset.head()

       z      tip    sleeve        Rf soil_type
0  0.025  13.7644   48.9334  0.355507      Sand
1  0.050  55.0427   68.6599  0.124739      Sand
2  0.075  50.4913   88.3865  0.175053      Sand
3  0.100  32.7215   98.6328  0.301431      Sand
4  0.125  33.5907  145.0764  0.431895      Sand

Machine Learning Model Development

In [11]:
#Giving the Machine Learning Model its inputs and target variable
X = dataset[['tip' , 'sleeve' , 'z']] #inputs
Y = dataset[['soil_type']] #target variable

In [12]:
#Splitting the data into target data and test data
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size = 0.2, random_state = 2 )

In [13]:
#Bringing random forest model into action
model = RandomForestClassifier()
# Assigning the train data to the model to understand and evaluate
model.fit(X_train , Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [14]:
#Testing the model with the test data we seperated from our base data
prediction = model.predict(X_test)

Model Evaluation

In [15]:
#Now the model is evaluated and the accuracy is calculated
print('Accuracy : ' , accuracy_score(Y_test , prediction))

Accuracy :  0.9032258064516129

In [16]:
# now we need the classification report
print(classification_report(Y_test , prediction))

              precision    recall  f1-score   support

        Clay       0.77      0.67      0.71        15
        Sand       1.00      0.75      0.86         8
        Silt       0.85      0.89      0.87        71
  Silty Sand       0.94      0.95      0.95       123

    accuracy                           0.90       217
   macro avg       0.89      0.81      0.85       217
weighted avg       0.90      0.90      0.90       217